name: ARI4Java Build

on:
  push:
    branches:
    - master
    - gb-wip
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :codegen:runCodegen build
    - name: Archive Reports
      uses: actions/upload-artifact@v1
      with:
        name: report-folder
        path: build/reports
